In [1]:
import numpy as np
from time import time

In [3]:
d,N=1000,10000
X=np.random.randn(N,d)
z=np.random.randn(d)

In [5]:
def dist_pp(z,x):
    d=z-x
    return sum(d*d)

In [8]:
def dist_ps_naive(z,X):
    res=np.zeros((1,N))
    for i in range(N):
        res[0][i]=dist_pp(z,X[i])
    return res

In [14]:
def dist_ps_fast(z,X):
    X2=np.sum(X*X,1)
    z2=np.sum(z*z)
    return X2+z2-2*X.dot(z)

In [18]:
t1 = time()
D1 = dist_ps_naive(z, X)
print("naive point2set, running time:", time() - t1, "s")
t1 = time()
D2 = dist_ps_fast(z, X)
print("fast point2set , running time:", time() - t1, "s")
print("Result difference:", np.linalg.norm(D1 - D2))

naive point2set, running time: 1.5690827369689941 s
fast point2set , running time: 0.09626364707946777 s
Result difference: 1.5905792162766028e-10


In [24]:
X.reshape(-1,1)

array([[-0.20923206],
       [-2.2080198 ],
       [ 1.57356354],
       ...,
       [-0.34226796],
       [-0.37124851],
       [ 1.98979158]])

In [34]:
test1=np.random.randn(2,2)
test2=np.random.randn(2)

In [35]:
test1

array([[-0.25661011, -0.05514656],
       [-0.68286879,  0.34178106]])

In [36]:
test2

array([ 0.8208423 , -0.45055796])

In [39]:
test1.dot(test2)

array([-0.18578972, -0.71451977])

# sklearn

In [41]:
from sklearn.model_selection import train_test_split
from sklearn import neighbors,datasets
from sklearn.metrics import accuracy_score

In [42]:
np.random.seed(7)
iris=datasets.load_iris()
iris_X=iris.data
iris_y=iris.target

In [43]:
print("Labels: ",np.unique(iris_y))

Labels:  [0 1 2]


In [44]:
X_train,X_test,y_train,y_test=train_test_split(iris_X,iris_y,test_size=130)
print("Train size: ",X_train.shape[0],", test size: ",X_test.shape[0])

Train size:  20 , test size:  130


In [45]:
model=neighbors.KNeighborsClassifier(n_neighbors=1,p=2)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [54]:
print(f"Accuracy of 1NN: {(100*accuracy_score(y_test,y_pred)):.2f} %")

Accuracy of 1NN: 92.31 %


In [56]:
model=neighbors.KNeighborsClassifier(n_neighbors=7,p=2)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [57]:
print(f"Accuracy of 7NN: {(100*accuracy_score(y_test,y_pred)):.2f} %")

Accuracy of 7NN: 93.85 %
